import { buildIndex } from "../dist/indexer/index.js";
import { writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Walk up from script location to find the repo root (where packages/components lives)
let projectRoot = resolve(__dirname, "..", "..");
for (let i = 0; i < 3; i++) {
  if (existsSync(resolve(projectRoot, "packages", "components"))) break;
  projectRoot = resolve(projectRoot, "..");
}

if (!existsSync(resolve(projectRoot, "packages", "components"))) {
  console.error(
    `[@ioca/react-mcp] ERROR: packages/components not found. Cannot build index.`,
  );
  process.exit(1);
}

const index = buildIndex(projectRoot);

// Write generated TypeScript module into api/ so Vercel bundles it automatically
const apiDir = resolve(__dirname, "..", "api");
const generated =
  "// Auto-generated by scripts/generate-index.js — do not edit manually\n" +
  "\n" +
  `export const generatedIndex = ${JSON.stringify({
    version: index.version,
    indexedAt: index.indexedAt,
    components: Array.from(index.components.entries()),
    sharedTypes: index.sharedTypes,
  })};\n`;

writeFileSync(resolve(apiDir, "generated-index.ts"), generated);

console.error(
  `[@ioca/react-mcp] Pre-built index saved to api/generated-index.ts (${index.components.size} components, ${index.sharedTypes.length} shared types)`,
);
